# Generated by cpp11: do not edit by hand

log_prob <- function(ext_model_ptr, upars) {
  .Call(`_rstandev_log_prob`, ext_model_ptr, upars)
}

grad_log_prob <- function(ext_model_ptr, upars) {
  .Call(`_rstandev_grad_log_prob`, ext_model_ptr, upars)
}

get_param_names <- function(ext_model_ptr) {
  .Call(`_rstandev_get_param_names`, ext_model_ptr)
}

get_dims <- function(ext_model_ptr) {
  .Call(`_rstandev_get_dims`, ext_model_ptr)
}

unconstrain_pars <- function(ext_model_ptr, pars) {
  .Call(`_rstandev_unconstrain_pars`, ext_model_ptr, pars)
}

constrain_pars <- function(ext_model_ptr, upars) {
  .Call(`_rstandev_constrain_pars`, ext_model_ptr, upars)
}

stan_methods_wrapper <- function(name, args) {
  .Call(`_rstandev_stan_methods_wrapper`, name, args)
}
